# seed
random_seed: 13

# data
dataset_type: 'spatio_temporal_data'
data_Y_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/GPLVM_project_code/data/climate_data/tensors/temperature.pt'
data_lat_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/GPLVM_project_code/data/climate_data/tensors/latitude.pt'
data_lon_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/GPLVM_project_code/data/climate_data/tensors/longitude.pt'

# input
min_input_bound: 0 
max_input_bound: 10 
inputs_period:  # None

# model
n_outputs: 1131
n_input: 363
n_input_train: 289
n_input_test: 74
n_inducing_input: 20
batch_size_input: 20
learn_inducing_locations: True
kernel_type: 'Scale_Periodic_times_Scale_RBF'

# model initialization
2thKernel_raw_lengthscale_init: 20.
init_likelihood_raw_noise: -2.973 # noise value = 0.05 (ground truth)
init_inducing_input_LB: 0
init_inducing_input_UB: 10

# optimizer
lr: 0.01
step_size: 20
gamma: 0.95

# training
n_iterations: 5000
model_max_grad_norm: 1
likeli_max_grad_norm: 0.1

# save
model_and_likelihood_path: '/Users/jiangxiaoyu/Desktop/All Projects/GPLVM_project_code/experi_results/MultiIGPs_models_and_likelihoods.pth'
store_all_loss: True
all_training_loss_file: '/Users/jiangxiaoyu/Desktop/All Projects/GPLVM_project_code/experi_results/all_training_loss.csv'


